### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'in_mem' in undefined

### ISSUE THREAD

**Issue by shookware** [hansec/autocomplete-fortran#9]
1. selected set procedure of the points in my project and select "fortran go-declaration".
2. the code block is 

 ```
 type :: grid2d_type
      integer :: in, jn
       type(point_type) :: points(in, jn)
  end type grid2d_type  

   Subroutine set(this, xx, yy, zz)

        Implicit None
        Class(grid2d_type) :: this
        real(8), Dimension(:, :) :: xx, yy, zz

        Call this%points%Set(xx, yy, zz)

    End Subroutine set
```

the code define type point_type is in another .f90 file

```
    type, public :: point_type

        real(8), private :: x(3) !

        Contains

          Procedure :: Set  

    end type point_type
```

when I paste these code in another new project. it has no error. but when I use this code in my old project, the error is coming.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-fortran](https://github.com/hansec/autocomplete-fortran) package 0.9.4

### Stack Trace

Uncaught TypeError: Cannot use 'in' operator to search for 'in_mem' in undefined

```
At /Users/shookware/.atom/packages/autocomplete-fortran/lib/fortran-provider.coffee:838

TypeError: Cannot use 'in' operator to search for 'in_mem' in undefined
    at FortranProvider.module.exports.FortranProvider.resolveIherited (/packages/autocomplete-fortran/lib/fortran-provider.coffee:838:8)
    at FortranProvider.module.exports.FortranProvider.goToDef (/packages/autocomplete-fortran/lib/fortran-provider.coffee:483:8)
    at Object.goDeclaration (/packages/autocomplete-fortran/lib/autocomplete-fortran.coffee:62:24)
    at /packages/autocomplete-fortran/lib/autocomplete-fortran.coffee:41:53)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:56 editor:indent (input.hidden-input)
 15x -1:55.4.0 core:backspace (input.hidden-input)
  2x -1:45.1.0 core:save (input.hidden-input)
  2x -1:36.1.0 editor:cut-to-end-of-line (input.hidden-input)
  3x -1:34.8.0 core:save (input.hidden-input)
  2x -1:20.8.0 tabs:close-other-tabs (div.title)
     -0:55.6.0 tabs:close-tabs-to-right (div.title)
     -0:51.6.0 tabs:close-all-tabs (div.title)
     -0:41.3.0 core:backspace (input.hidden-input)
  2x -0:40.6.0 core:save (input.hidden-input)
     -0:32.9.0 editor:newline (input.hidden-input)
  2x -0:29.1.0 core:move-down (input.hidden-input)
     -0:28.4.0 autocomplete-plus:confirm (input.hidden-input)
 16x -0:26.5.0 core:backspace (input.hidden-input)
  2x -0:22.8.0 core:save (input.hidden-input)
     -0:12.9.0 autocomplete-fortran:go-declaration (span.syntax--meta.syntax--variable.syntax--fortran)
```

### Non-Core Packages

```
autocomplete-fortran 0.9.4 
language-fortran 2.1.0 
```

**Comment by hansec** [comment]
Sorry for the wait. However, as you said using this code alone in a new project doesn't produce an error. Can you try and produce a reduced test case or if possible send the full files relating to the issue? Thanks!
